#!/usr/bin/perl -w

# Ansagedateien fuer das Wiregate-Plugin Ansagen.pl in /var/lib/mpd/music/Ansagen schreiben
# Quelle fuer die Dateien ist Google

use strict;

system "mkdir", "-p", "/var/lib/mpd/music/Ansagen";
chdir "/var/lib/mpd/music/Ansagen";

my %text=(
    "./Achtung Einbruch.wav"=>"Achtung Einbruch Verlassen Sie sofort das Haus",
    "./AufWiedersehen.wav"=>"Auf Wiedersehen",
    "./Tschuess.wav"=>"tschuess",
    "./Achtung.wav"=>"Achtung",
    "./Ciao.wav"=>"tschau",
    "./Bitte Schluesselbund ans Schluesselbrett haengen.wav"=>"Bitte Schluesselbund ans Schluesselbrett haengen",
    "./Der Trockner ist fertig.wav"=>"Der Trockner ist fertig",
    "./Bitte Papiermuell rausstellen.wav"=>"Bitte Papiermuell rausstellen",
    "./Bitte Biomuell rausstellen.wav"=>"Bitte Biomuell rausstellen",
    "./Bitte Restmuell rausstellen.wav"=>"Bitte Restmuell rausstellen",
    "./Die Alarmanlage ist aktiviert.wav"=>"Die Alarmanlage ist aktiviert",
    "./Die Alarmanlage ist deaktiviert.wav"=>"Die Alarmanlage ist deaktiviert",
    "./Die Alarmanlage wird in fuenf Minuten aktiviert.wav"=>"Die Alarmanlage wird in fuenf Minuten aktiviert",
    "./Die Waschmaschine ist fertig.wav"=>"Die Waschmaschine ist fertig",
    "./Es liegt neue Post im Briefkasten.wav"=>"Es liegt neue Post im Briefkasten",
    "./Essen ist fertig.wav"=>"Essen ist fertig",
    "./Fenster offen.wav"=>"Fenster offen",
    "./Kaffee ist fertig.wav"=>"Kaffee ist fertig",
    "./Monate/April.wav"=>"April",
    "./Monate/August.wav"=>"August",
    "./Monate/Dezember.wav"=>"Dezember",
    "./Monate/Februar.wav"=>"Februar",
    "./Monate/Januar.wav"=>"Januar",
    "./Monate/Juli.wav"=>"Juli",
    "./Monate/Juni.wav"=>"Juni",
    "./Monate/Maerz.wav"=>"Maerz",
    "./Monate/Mai.wav"=>"Mai",
    "./Monate/November.wav"=>"November",
    "./Monate/Oktober.wav"=>"Oktober",
    "./Monate/September.wav"=>"September",
    "./Personen/Alois.wav"=>"Alois",
    "./Personen/Andrea.wav"=>"Andrea",
    "./Personen/Christoph.wav"=>"Christoph",
    "./Personen/Chris.wav"=>"Chris",
    "./Personen/Guenther.wav"=>"Guenther",
    "./Personen/Helena.wav"=>"Helena",
    "./Personen/Jakob.wav"=>"Jakob",
    "./Personen/Jasmin.wav"=>"Jasmin",
    "./Personen/Julius.wav"=>"Julius",
    "./Personen/Kim.wav"=>"Kim",
    "./Personen/Lynn.wav"=>"Lynn",
    "./Personen/Michael.wav"=>"Michael",
    "./Personen/Nils.wav"=>"Nils",
    "./Personen/Rita.wav"=>"Ritah",
    "./Personen/Jule.wav"=>"Jule",
    "./Personen/Tanja.wav"=>"Tanja",
    "./Personen/Uta.wav"=>"Uta",
    "./Personen/Wigbert.wav"=>"Wigbert",
    "./Personen/Gast.wav"=>"Gast",
    "./Rauchalarm.wav"=>"Rauchalarm",
    "./Raum/A1.wav"=>"Aussenbereich unten",
    "./Raum/A2.wav"=>"Aussenbereich oben",
    "./Raum/AT.wav"=>"Aussentreppe",
    "./Raum/AZ.wav"=>"Arbeitszimmer",
    "./Raum/BA.wav"=>"Grosses Bad",
    "./Raum/D1.wav"=>"Dusche Keller",
    "./Raum/D2.wav"=>"Dusche Erdgeschoss",
    "./Raum/DA.wav"=>"Dach",
    "./Raum/EK.wav"=>"Esskueche",
    "./Raum/E.wav"=>"Eingangsflur",
    "./Raum/F2.wav"=>"Flur Erdgeschoss",
    "./Raum/GA.wav"=>"Galerie",
    "./Raum/GL.wav"=>"Global",
    "./Raum/G.wav"=>"Garage",
    "./Raum/HE.wav"=>"Heizung",
    "./Raum/HW.wav"=>"Hauswirtschaftsraum",
    "./Raum/K1.wav"=>"K1",
    "./Raum/K2.wav"=>"K2",
    "./Raum/K3b.wav"=>"K3",
    "./Raum/K3.wav"=>"K3",
    "./Raum/SZ.wav"=>"Schlafzimmer",
    "./Raum/TE2.wav"=>"Terrasse",
    "./Raum/TE3.wav"=>"Balkon",
    "./Raum/TR1.wav"=>"Eingangstreppe",
    "./Raum/TR2.wav"=>"Galerietreppe",
    "./Raum/UT.wav"=>"Unter der Treppe",
    "./Raum/VO.wav"=>"Vorratsraum",
    "./Raum/WF.wav"=>"Windfang",
    "./Raum/WZ.wav"=>"Wohnzimmer",
    "./Sensor/KA.wav"=>"Aufzug",
    "./Sensor/KF.wav"=>"Fenster",
    "./Sensor/KO.wav"=>"Kontakt",
    "./Sensor/KR.wav"=>"Relais",
    "./Sensor/KS.wav"=>"Stromfluss",
    "./Sensor/KT.wav"=>"Tuer",
    "./Sensor/LF.wav"=>"Luftfeuchte",
    "./Sensor/PM.wav"=>"Praesenz",
    "./Sensor/TA.wav"=>"Aussentemperatur",
    "./Sensor/TE.wav"=>"Estrich",
    "./Sensor/TL.wav"=>"Innentemperatur",
    "./Sensor/TO.wav"=>"Temperatur",
    "./Sensor/TP.wav"=>"Taupunkt",
    "./Sensor/VC.wav"=>"Wok",
    "./Willkommen.wav"=>"Willkommen",
    "./Hi.wav"=>"Hai",
    "./Hallo.wav"=>"Hallo",
    "./Wochentage/Di.wav"=>"Dienstag",
    "./Wochentage/Do.wav"=>"Donnerstag",
    "./Wochentage/Fri.wav"=>"Freitag",
    "./Wochentage/Fr.wav"=>"Freitag",
    "./Wochentage/Mi.wav"=>"Mittwoch",
    "./Wochentage/Mon.wav"=>"Montag",
    "./Wochentage/Mo.wav"=>"Montag",
    "./Wochentage/Sat.wav"=>"Samstag",
    "./Wochentage/Sa.wav"=>"Samstag",
    "./Wochentage/So.wav"=>"Sonntag",
    "./Wochentage/Sun.wav"=>"Sonntag",
    "./Wochentage/Thu.wav"=>"Donnerstag",
    "./Wochentage/Tue.wav"=>"Dienstag",
    "./Wochentage/Wed.wav"=>"Mittwoch",
    "./Woerter/Bett.wav"=>"Bett",
    "./Woerter/Decke.wav"=>"Decke",
    "./Woerter/Herd.wav"=>"Herd",
    "./Woerter/Kamin.wav"=>"Kamin",
    "./Woerter/links.wav"=>"links",
    "./Woerter/rechts.wav"=>"rechts",
    "./Woerter/Spuele.wav"=>"Spuele",
    "./Woerter/unter_Galerie.wav"=>"unter_Galerie",
    "./Woerter/unter_Treppe.wav"=>"unter_Treppe",
    "./Zahlen/an.wav"=>"an",
    "./Zahlen/auf.wav"=>"auf",
    "./Zahlen/aus.wav"=>"aus",
    "./Zahlen/ab.wav"=>"ab",
    "./Zahlen/stop.wav"=>"stop",
    "./Zahlen/c0.wav"=>"Null",
    "./Zahlen/c1000.wav"=>"tausend",
    "./Zahlen/c100.wav"=>"hundert",
    "./Zahlen/c10.wav"=>"zehn",
    "./Zahlen/c11.wav"=>"elf",
    "./Zahlen/c12.wav"=>"zwoelf",
    "./Zahlen/c13.wav"=>"dreizehn",
    "./Zahlen/c14.wav"=>"vierzehn",
    "./Zahlen/c15.wav"=>"fuenfzehn",
    "./Zahlen/c16.wav"=>"sechzehn",
    "./Zahlen/c17.wav"=>"siebzehn",
    "./Zahlen/c18.wav"=>"achtzehn",
    "./Zahlen/c19.wav"=>"neunzehn",
    "./Zahlen/c1.wav"=>"eins",
    "./Zahlen/c20.wav"=>"zwanzig",
    "./Zahlen/c2.wav"=>"zwei",
    "./Zahlen/c30.wav"=>"dreissig",
    "./Zahlen/c3.wav"=>"drei",
    "./Zahlen/c40.wav"=>"vierzig",
    "./Zahlen/c4.wav"=>"vier",
    "./Zahlen/c50.wav"=>"fuenfzig",
    "./Zahlen/c5.wav"=>"fuenf",
    "./Zahlen/c60.wav"=>"sechzig",
    "./Zahlen/c6.wav"=>"sechs",
    "./Zahlen/c70.wav"=>"siebzig",
    "./Zahlen/c7.wav"=>"sieben",
    "./Zahlen/c80.wav"=>"achtzig",
    "./Zahlen/c8.wav"=>"acht",
    "./Zahlen/c90.wav"=>"neunzig",
    "./Zahlen/c9.wav"=>"neun",
    "./Zahlen/Grad.wav"=>"Grad",
    "./Zahlen/hoch.wav"=>"hoch",
    "./Zahlen/Komma.wav"=>"Komma",
    "./Zahlen/minus.wav"=>"minus",
    "./Zahlen/o0.wav"=>"Nullter",
    "./Zahlen/o1000.wav"=>"Tausendster",
    "./Zahlen/o100.wav"=>"Hundertster",
    "./Zahlen/o10.wav"=>"Zehnter",
    "./Zahlen/o11.wav"=>"Elfter",
    "./Zahlen/o12.wav"=>"Zwoelfter",
    "./Zahlen/o13.wav"=>"Dreizehnter",
    "./Zahlen/o14.wav"=>"Vierzehnter",
    "./Zahlen/o15.wav"=>"Fuenfzehnter",
    "./Zahlen/o16.wav"=>"Sechzehnter",
    "./Zahlen/o17.wav"=>"Siebzehnter",
    "./Zahlen/o18.wav"=>"Achtzehnter",
    "./Zahlen/o19.wav"=>"Neunzehnter",
    "./Zahlen/o1.wav"=>"Erster",
    "./Zahlen/o20.wav"=>"Zwanzigster",
    "./Zahlen/o2.wav"=>"Zweiter",
    "./Zahlen/o30.wav"=>"Dreissigster",
    "./Zahlen/o3.wav"=>"Dritter",
    "./Zahlen/o40.wav"=>"Vierzigster",
    "./Zahlen/o4.wav"=>"Vierter",
    "./Zahlen/o50.wav"=>"Fuenfzigster",
    "./Zahlen/o5.wav"=>"Fuenfter",
    "./Zahlen/o60.wav"=>"Sechzigster",
    "./Zahlen/o6.wav"=>"Sechster",
    "./Zahlen/o70.wav"=>"Siebzigster",
    "./Zahlen/o7.wav"=>"Siebter",
    "./Zahlen/o80.wav"=>"Achtzigster",
    "./Zahlen/o8.wav"=>"Achter",
    "./Zahlen/o90.wav"=>"Neunzigster",
    "./Zahlen/o9.wav"=>"Neunter",
    "./Zahlen/Prozent.wav"=>"Prozent",
    "./Zahlen/runter.wav"=>"runter",
    "./Zahlen/u1.wav"=>"ein",
    "./Zahlen/u2.wav"=>"zwei",
    "./Zahlen/u3.wav"=>"drei",
    "./Zahlen/u4.wav"=>"vier",
    "./Zahlen/u5.wav"=>"fuenf",
    "./Zahlen/u6.wav"=>"sechs",
    "./Zahlen/u7.wav"=>"sieben",
    "./Zahlen/u8.wav"=>"acht",
    "./Zahlen/u9.wav"=>"neun",
    "./Zahlen/uc20.wav"=>"und zwanzig",
    "./Zahlen/uc30.wav"=>"und dreissig",
    "./Zahlen/uc40.wav"=>"und vierzig",
    "./Zahlen/uc50.wav"=>"und fuenfzig",
    "./Zahlen/uc60.wav"=>"und sechzig",
    "./Zahlen/uc70.wav"=>"und siebzig",
    "./Zahlen/uc80.wav"=>"und achtzig",
    "./Zahlen/uc90.wav"=>"und neunzig",
    "./Zahlen/uo20.wav"=>"und zwanzigster",
    "./Zahlen/uo30.wav"=>"und dreissigster",
    "./Zahlen/uo40.wav"=>"und vierzigster",
    "./Zahlen/uo50.wav"=>"und fuenfzigster",
    "./Zahlen/uo60.wav"=>"und sechzigster",
    "./Zahlen/uo70.wav"=>"und siebzigster",
    "./Zahlen/uo80.wav"=>"und achtzigster",
    "./Zahlen/uo90.wav"=>"und neunzigster",
    "./Zahlen/zu.wav"=>"zu",
    "./Zeiten/Minuten.wav"=>"Minuten",
    "./Zeiten/Sekunden.wav"=>"Sekunden",
    "./Zeiten/Stunden.wav"=>"Stunden",
    "./Zeiten/Uhr.wav"=>"Uhr",
    "./Warnung/keine_Meldung.wav"=>"keine Meldung",
    "./Warnung/Hinweis.wav"=>"Hinweis",
    "./Warnung/Vorwarnung.wav"=>"Vorwarnung",
    "./Warnung/Warnung.wav"=>"Warnung",
    "./Warnung/Gefahr.wav"=>"Gefahr",
    "./Warnung/Gefahr_hoch.wav"=>"Gefahr hoch",
    "./Unwetter/Gewitter.wav"=>"Gewitter",
    "./Unwetter/Glatteis.wav"=>"Glatteis",
    "./Unwetter/Regen.wav"=>"Regen",
    "./Unwetter/Schnee.wav"=>"Schnee",
    "./Unwetter/Sturm.wav"=>"Sturm",
    "./Unwetter/Temperatur.wav"=>"Temperatur",
    "./Unwetter/Strassenglaette.wav"=>"Strassenglaette",
);

for my $f (keys %text)
{
    my $t=$text{$f};
    $t=~s/ /\%20/g;
    my $p=$f; $p=~s!/[^/]*$!!;
    my $m=$f; $m=~s!\.wav$!.mp3!;
    next if -f $f;
    system "mkdir", "-p", $p; 
    system "wget", "http://translate.google.de/translate_tts?ie=UTF-8&q=$t&tl=de", "--keep-session-cookies", "--user-agent=sag_ich_nicht", "-O", $m;
    system "mpg123", "-w", $f, $m;
    system "rm", "-f", "tmp.wav", "tmp2.wav";
    system "sox", $f, "tmp.wav", "silence", "1", "0.001", "0.2%", "1", "0.3", "0.1%";
    system "sox", "tmp.wav", "tmp2.wav", "tempo", "1.5";
    system "mv", "tmp2.wav", $f;
    system "rm", "-f", "tmp.wav";
    system "rm", "-f", $m;
}

for my $d (1..5)
{
    my $l=sprintf("%0.1f",0.2*$d);
    my $f=sprintf("sil%dms.wav", 1000*$l);
    next if -f $f; 
    system "sox", "-n", "-r", "44100", "-c", "2", $f, "trim", "0.0", $l;
}

system "ln -sf sil200ms.wav silence.wav";
